### ISSUE TITLE
ProvePossession -- verify proof

### ISSUE THREAD

**Issue by ZenGround0** [FILCAT/pdp#10]
1. Use challenge index with SumTree search (#8 ) to find root to prove against
2. Verify merkle proof argument against root id hash 

Things adding uncertainty
* we should find and import a good merkle proving library which has handled lots of proving.  @nicola has done some investigation into this IIRC.
* we need to figure out cids vs no cids in our proofs

**Comment by nicola** [comment]
I did a first pass at this here: https://github.com/nicola/fws-service/blob/main/contracts/FWS.sol

There are other libraries that are audited, might be worth looking into those too.
