### ISSUE TITLE
Move record keeping to external contract

### ISSUE THREAD

**Issue by ZenGround0** [FILCAT/pdp#13]
1. Repurpose the functions that track operations in the record keeping state to now call into an external contract
2. Create record keeping contract type, new solidity file
3. Initialization of record keeping contract state and functions for setting an expected caller
4. PDP Service contract allows for write once setting of the push notifee (alternatively we could have this piece of state be externally owned).  Push to a single notifee always.

Uncertainty
* Exactly how does setting expected caller of record keeping contract work?  Ownership model, write-once? 
* Maybe we should revisit exactly how the setting push notification receiver works.  
* Should we swallow communication errors?  Probably not. Are there any security issues where the caller can maliciously avoid updates to manipulate the record in their favor?  I don't think so but we should think more carefully.

**Comment by anorth** [comment]
> write once setting of the push notifee

Per proof set?
