### ISSUE TITLE
Proof set add 

### ISSUE THREAD

**Issue by ZenGround0** [FILCAT/pdp#6]
Implement Proof set add

1. Implement the add function on the [sum tree](https://docs.google.com/document/d/16VtbihsKDEjzcCWJl0Rdz_M72itPzoM9GKZC1wgiB3Y/edit) data structure.
2. Implement full proof set add including root add and calling sum tree add

**Comment by anorth** [comment]
I think the API here should be a batch of additions to the same proof set.
